name: lekkerly
description: "A fun and modern app for learning the Dutch language."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flip_card: ^0.7.0
  flutter_tts: ^3.8.3
  audioplayers: ^5.2.1
  confetti: ^0.7.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  provider: ^6.1.1
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/vocabulary.json
    - assets/sounds/
    - assets/images/
